[config]

[templates.quickshell]
input_path = 'templates/quickshell-theme.json'
output_path = '~/.config/quickshell/Assets/Themes/Dynamic/Colors.json'

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
