# How the image is parsed in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "fastresize"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
#check_contrast = true

#saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }
quickshell = { template = 'quickshell', target = '~/.config/quickshell/Settings/Theme.json' }
